const REACT_APP_POTTER_API_KEY = '$2a$10$FAmRL8kl.Tj9hRCETvgTZepeyWrUVbeXEjfv8hkwggalFWOwsu1im';
const REACT_APP_ZOMATO_API_KEY = 'd597c83e846626cb8f8479334055fba9';
const REACT_APP_UNSPLASH_API_KEY = 'DZtGI3mwqNRVryoipusIJD_fYr1453aSYEOWI3r8RpU';
const REACT_APP_GOOGLE_API_KEY = 'AIzaSyAMDv1BXSmolDH7o5fRWsMKSS-rDiQSCjo';
const REACT_APP_MAPBOX_TOKEN = 'pk.eyJ1IjoiZ3JvdmVyamF0aW4xNyIsImEiOiJjazk2ejZiMTUwZDJtM2RsaXZxZXU5bTNiIn0.HDYY3UJS6o9rVBdRhPTx-g';


export {
    REACT_APP_POTTER_API_KEY, 
    REACT_APP_ZOMATO_API_KEY, 
    REACT_APP_UNSPLASH_API_KEY, 
    REACT_APP_GOOGLE_API_KEY,
    REACT_APP_MAPBOX_TOKEN
};
